# Generated by Django 6.0 on 2026-02-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtranslation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogtranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
