# Generated by Django 6.0 on 2026-02-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_translation_nullable_title_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content", models.TextField(blank=True, default="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/sections/")),
                ("blog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="blogs.blog")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
