# Generated by Django 6.0 on 2026-02-19 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogsection'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogsection',
            name='title',
        ),
        migrations.CreateModel(
            name='BlogSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('blog_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_section_translations', to='blogs.blogsection')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
