# Generated by Django 6.0 on 2026-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_ip_address_alter_subscriber_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('name', 'email', 'message'), name='unique_contact_submission'),
        ),
    ]
