# Generated by Django 6.0 on 2026-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_assets', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestionstranslation',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partnerstranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='frequentlyaskedquestionstranslation',
            unique_together={('frequently_asked_question', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerstranslation',
            unique_together={('partner', 'language')},
        ),
    ]
