# Generated by Django 6.0 on 2026-02-17 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='member', max_length=20)),
                ('can_create_blog', models.BooleanField(default=False)),
                ('can_edit_blog', models.BooleanField(default=False)),
                ('can_delete_blog', models.BooleanField(default=False)),
                ('can_publish_blog', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_create_media', models.BooleanField(default=False)),
                ('can_edit_media', models.BooleanField(default=False)),
                ('can_delete_media', models.BooleanField(default=False)),
                ('can_manage_subscribers', models.BooleanField(default=False)),
                ('can_manage_contacts', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
