# Generated by Django 6.0 on 2026-02-18 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_userroles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='id',
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='role_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
