# Generated by Django 6.0 on 2026-02-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userroles_id_alter_userroles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='name',
        ),
    ]
